"""Git / GitHub operations backing the `commit` and `pr` action modes.

Deliberately free of pipeline logic so it can be unit-tested against a
throwaway git repository. The GitHub PR API is the only part that needs the
live service; it is skipped (with a warning) when GITHUB_TOKEN /
GITHUB_REPOSITORY are absent, so `pr` mode degrades gracefully off-CI.
"""
from __future__ import annotations

import os
import subprocess

DEFAULT_BRANCH = "repodocmake/update-docs"
DEFAULT_MESSAGE = "docs: update generated documentation [repodocmake]"
_PR_BODY = (
    "Automated documentation update generated by "
    "[RepoDocMake](https://github.com/Pablo-korea/repodocmake).\n\n"
    "These docs were synthesized from the repository's code and validated by "
    "the consistency gate. Please review before merging."
)


def _git(args: list[str], cwd: str) -> str:
    result = subprocess.run(
        ["git", *args], cwd=cwd, check=True, capture_output=True, text=True
    )
    return result.stdout.strip()


def _ensure_identity(cwd: str) -> None:
    """Set a commit identity only if the repo doesn't already have one."""
    try:
        _git(["config", "user.email"], cwd)
    except subprocess.CalledProcessError:
        _git(["config", "user.email",
              os.environ.get("REPODOCMAKE_GIT_EMAIL", "repodocmake-bot@users.noreply.github.com")], cwd)
        _git(["config", "user.name",
              os.environ.get("REPODOCMAKE_GIT_NAME", "repodocmake[bot]")], cwd)


def stage_and_commit(repo: str, filenames: list[str], message: str = DEFAULT_MESSAGE) -> bool:
    """Stage the given files and commit. Returns False if nothing changed."""
    if not filenames:
        return False
    _ensure_identity(repo)
    _git(["add", "--", *filenames], repo)
    if not _git(["status", "--porcelain", "--", *filenames], repo):
        return False  # nothing actually staged
    _git(["commit", "-m", message], repo)
    return True


def commit_mode(repo: str, filenames: list[str], message: str = DEFAULT_MESSAGE) -> bool:
    """Commit generated docs directly onto the current branch."""
    return stage_and_commit(repo, filenames, message)


def pr_mode(
    repo: str,
    filenames: list[str],
    *,
    branch: str = DEFAULT_BRANCH,
    message: str = DEFAULT_MESSAGE,
    base: str | None = None,
) -> str | None:
    """Commit docs to a fresh branch, push it, and open a PR.

    Returns the PR URL, or None if nothing changed or the GitHub API was
    skipped (no token / repo slug in the environment).
    """
    _ensure_identity(repo)
    _git(["checkout", "-B", branch], repo)
    if not stage_and_commit(repo, filenames, message):
        return None
    _git(["push", "--force", "origin", branch], repo)
    return open_github_pr(branch, base=base, title=message)


def open_github_pr(head: str, *, base: str | None, title: str) -> str | None:
    token = os.environ.get("GITHUB_TOKEN")
    repo_slug = os.environ.get("GITHUB_REPOSITORY")
    if not token or not repo_slug:
        print("::warning::GITHUB_TOKEN / GITHUB_REPOSITORY not set — skipping PR creation.")
        return None
    from github import Github

    gh_repo = Github(token).get_repo(repo_slug)
    pr = gh_repo.create_pull(
        title=title, body=_PR_BODY, head=head, base=base or gh_repo.default_branch
    )
    return pr.html_url
